
<?php

$channelsDict = [
    'AMGD' => '美东Amazon Ground',
    'FEDHDE' => '美东FedEx HomeDelivery',
    'FEDHDEMP' => '美东FedEx HD Multiple子母单',
    'UPSGDE' => '美东UPS Ground',
    'NJUSPSGA' => '美东USPS Ground（磅内磅上）',
    'USPSPME' => '美东USPS Priority Mail',
    'SPEEDXNJ' => '美东SpeedX(磅内磅上)',
    'FDXSPE' => '美东FedEx SmartPost',
    'UNIUNINJ' => '美东UniUni(磅内磅上)',
    'GOFONJ' => '美东GOFO Express',
    'GFYUNNJ' => '美东GOFO YunExpress',
    'AMGDCA' => '美西Amazon Ground',
    'UPSGW' => '美西UPS Ground',
    'CAUSPSGA' => '美西USPS Ground（磅内磅上）',
    'USPSPMW' => '美西USPS Priority Mail',
    'USPSGACASG' => '美西USPS Ground（磅内磅上）签名',
    'FEDHDW' => '美西FedEx HomeDelivery',
    'FEDHDWMP' => '美西FedEx HD Multiple子母单',
    'UPSGWFBA' => '美西UPS Ground FBA',
    'SPEEDXCA' => '美西SpeedX(磅内磅上)',
    'CAGLS' => '美西GLS',
    'FEDSPW' => '美西FedEx SmartPost',
    'UNIUNICA' => '美西UniUni(磅内磅上)',
    'GOFOCA' => '美西GOFO Express',
    'GFYUNCA' => '美西GOFO YunExpress',
    'FEDIGCA' => '美西FedEx International Ground-美发加',
    'FEDEX-GROUND-EA' => '美东FedEx重货',
    'SS-FEDEX-G-E' => '美东FEDEX大货渠道',
    'FEDEX-SM' => '美国FEDEX经济小包',
    'FEDEX-LP' => '美国FEDEX经济大包',
    'AMAZON-GROUND' => '美国AMAZON重货渠道',
    'USPS-FIRST-CLASS' => '美国USPS小包',
    'USPS-PRIORITY' => '美国USPS大包',
    'DHL-US-SP' => '美国DHL本地小包',
    'DHL-US-BP' => '美国DHL本地大包',
    'YUN-GROUND' => '美国YUN重货渠道',
    'CE-PARCEL' => '美国CE普货渠道',
    'CE-GROUND-EA' => '美东CE重货渠道',
    'UPS-GROUND-EA' => '美东UPS重货',
    'UPS-GROUND-MULT' => '美国UPS一票多箱',
    'UPS-SUREPOST' => 'UPS_SUREPOST',
    'UPS-2ND-DAY' => 'UPS两日达',
    'INT-PRI-SP' => '国际普快小包',
    'INT-PRI-LP' => '国际普快大包',
    'IPA-INT-ECONOMIC' => '国际经济小包',
    'US-G2G-INT' => '美加G2G国际渠道',
    'US-UPS-INT' => '美国UPS国际渠道',
    'FEDEX-GROUND' => '美国FEDEX重货渠道',
    'SS-FEDEX-G-W' => '美西FEDEX大货渠道',
    'CE-GROUND' => '美西CE重货渠道',
    'UPS-GROUND' => '美国UPS重货渠道',
    'OT-GROUND' => '美国OnTrac重货渠道'
];

echo $channelsDict['SPEEDXNJ'];